### ISSUE TITLE
External projects (e.g. xcfun) not correctly recompiled

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#66]
When an external submodule is modified (e.g. a file in the xcfun library), `make` does not trigger the recompilation of the library. With help from @robertodr I managed to trigger the library recompilation, but not the linking, which occurs only if a source of mrchem itself is recompiled.

**Comment by stigrj** [comment]
These kinds of problems have become much more prominent lately, especially related to header files and previously installed versions of the code. Known issues:
- When header files in the main project (`mrchem/src`) are updated, they are apparently not imported to all targets in `build-dir`. 
- If CMake finds an installed version of MRCPP, either globally or if the chosen  `--prefix=install-dir` already exists, it will use this version rather than compiling a new one. However, in this case the MRCPP include paths doesn't work. Reproducible example:
```
$ ./setup --prefix=install-dir build-dir
$ cd build-dir
$ make install
$ cd ..
$ rm -rf build-dir
$ ./setup --prefix=install-dir build-dir
$ cd build-dir
$ make install
[  1%] Building CXX object src/CMakeFiles/mrchem.dir/parallel.cpp.o
/home/stig/src/mrchem/src/parallel.cpp:1:10: fatal error: MRCPP/Printer: No such file or directory
 #include "MRCPP/Printer"
```

Currently the only safe thing during development is to avoid the `install` command and recompile the entire `build` tree at regular intervals
```
$ rm -rf build-dir
$ ./setup build-dir
$ cd build-dir
$ make
```
which of course is a pain.

**Comment by stigrj** [comment]
This seems to work in the new setup
