### ISSUE TITLE
DFT open shell input

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#71]
The MRChem input requires an explicit variable to use a spin-sparated functional. For open-shell systems, a separated functional should be the default, whereas the spin-restricted one might be activated in special circumstances (e.g. test against NIST results).

Default values in input handling shall be changed.

**Comment by susilehtola** [comment]
So how is one supposed to run spin-polarized DFT?

The manual at http://mrchem.readthedocs.io/en/latest/mrchem_manual.html is outdated since it appears the proper keyword is not ```spin_polarized``` but ```spin```. However, running with ```spin = true``` results in an error saying that spin DFT is not implemented...

**Comment by stigrj** [comment]
Unfortunately, spin-polarized DFT is not available in the current version, but will be very soon in the upcoming version.

**Comment by susilehtola** [comment]
So is the current DFT spin-restricted?

**Comment by stigrj** [comment]
Yes, only spin-restricted DFT, but both RHF and UHF. Also, note that the initial guess is not very good in the current version, and only `initial_guess = none` is possible unless you have precomputed MO coefficients and a corresponding LSDalton basis set file. This means that there is a fair chance that your computed energy is *not* going to be the global minimum. This will be much improved in the upcoming version :)

**Comment by stigrj** [comment]
Well, you will find a solution, but it might not be the global minimum :)

No, I have to apologize for the current condition of the code. We had a very old version that was able to do all this properly (including linear response), but we have rewritten the code in several stages since then and not yet caught up with ourselves. Also, it was dependent on a locally hacked version of LSDalton to provide a proper initial guess, and this was never intended for distribution. We are closing in on a proper v1.0 now, though, that should be able to do unrestricted ground state calculations on arbitrary systems. This should be available within a few weeks :crossed_fingers:

**Comment by stigrj** [comment]
Why are the issues not automagically closed through the commits?
